### ISSUE TITLE
访问测试链接有问题？

### ISSUE THREAD

**Issue by Jasonzhangjs** [cnblogs/BlogServer#4]
通过 https://i-beta.cnblogs.com/ 链接进入后，自动跳转到了 https://i-beta.cnblogs.com/mvc/NoBlog 页面，说没有开通博客不科学。

**Comment by cnblogs-team** [comment]
您好，您的邮箱并没有开通博客，因此跳到开通博客页面是正常的，建议您开通博客或者使用已开通的账号测试。感谢您的反馈和支持！
